# VRCMT.spec -- PyInstaller 6.x onefile build
import os, sys
block_cipher = None
PYTHON_SITE = os.path.join(os.path.dirname(sys.executable), "Lib", "site-packages")
added_files = [
    ("assets", "assets"),
    ("src", "src"),
    ("cred.json", "."),
    ("logo_tracker.ico", "."),
    (os.path.join(PYTHON_SITE, "babelfish", "data"), "babelfish/data"),
    (os.path.join(PYTHON_SITE, "babelfish", "converters"), "babelfish/converters"),
    (os.path.join(PYTHON_SITE, "guessit", "data"), "guessit/data"),
    (os.path.join(PYTHON_SITE, "guessit", "config"), "guessit/config"),
    (os.path.join(PYTHON_SITE, "wordninja"), "wordninja"),
]
hidden_imports = [
    "PySide6.QtNetwork",
    "PySide6.QtMultimedia",
    "shiboken6",
    "peewee",
    "guessit",
    "rebulk",
    "babelfish",
    "babelfish.converters",
    "babelfish.converters.alpha2",
    "babelfish.converters.alpha3b",
    "babelfish.converters.alpha3t",
    "babelfish.converters.countryname",
    "babelfish.converters.name",
    "babelfish.converters.opensubtitles",
    "babelfish.converters.scope",
    "babelfish.converters.type",
    "wordninja",
    "firebase_admin",
    "google.cloud.firestore",
    "google.auth",
    "google.auth.transport.requests",
    "google.oauth2.service_account",
    "httpx",
]
a = Analysis(
    ["main.py"],
    pathex=["."],
    binaries=[],
    datas=added_files,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "numpy", "scipy"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="VRCMT",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon="logo_tracker.ico",
)